layout_spectrum: 0.36003480618819594
typography_spectrum: 0.4385839581955224
color:
  brandStrength: 0.7572855886537582
  lightness: 0.8509675534442067
  saturation: 0.15068848198279738
  rhythmicContrast: 0.0042879898101091385
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
name: Assynt
navigation:
  - name: Tulips
    id: 407400cf-ba0e-44ca-a116-4db72d0371bd
    type: content
  - name: Flowers
    id: 7eacc85f-c2f5-4c98-99a0-f1ecb714cc7c
    type: content
  - name: Furry Tulips
    id: 96110f2e-692f-411a-b9ad-b1530e1002be
    type: content
  - name: Green and Purple
    id: b8f5e0b2-a0ed-441d-b630-931393eb7665
    type: content
